feat: add tts sample for long audio synthesis
GoogleCloudPlatform/python-docs-samples pull request #10001
Opened 2023-05-18 04:01 UTC by jameszhao00

Add a new sample for texttospeech long audio synthesis.

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2023-05-18 13:45 UTC, kweinmeister commented on texttospeech/snippets/synthesize_long_audio.py
> +# Copyright 2018 Google LLC
Use new copyright date 2023 for new samples

2023-05-18 13:46 UTC, kweinmeister commented on texttospeech/snippets/synthesize_long_audio.py
> +    voice = texttospeech.VoiceSelectionParams(
Consider making these constants, at the top of the sample. (Same comment applies to other options specified throughout sample.)

2023-05-18 13:48 UTC, kweinmeister commented on texttospeech/snippets/synthesize_long_audio_test.py
> +                                                           "gs://bucket/output.wav")
We should access sample data from the same location as other TTS samples (a standard Cloud sample data bucket)

(Also same comments about copyright year + constants)

2023-05-18 13:49 UTC, kweinmeister commented on texttospeech/snippets/synthesize_long_audio_test.py
> +def test_synthesize_text(capsys):
The sample method should return a value. And your test should check that the value is expected.

2023-05-25 20:18 UTC, engelke requested changes
Work out where to store and fetch the sample data, and add at least one test (assert).

2023-05-25 20:18 UTC, engelke commented on texttospeech/snippets/synthesize_long_audio_test.py
> +
There is no such bucket available. Also, there are no tests here.

2024-06-17 04:44 UTC, closed without merging