fixit: Clean up Python sample at compute/oslogin
GoogleCloudPlatform/python-docs-samples pull request #10067
Opened 2023-05-25 13:32 UTC by m-strzelczyk

## Description

Fixes b/280880980

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2023-05-25 15:57 UTC, rsamborski approved these changes

2023-05-25 20:08 UTC, engelke requested changes
Please return and test values instead of relying on captured output.

2023-05-25 20:08 UTC, engelke commented on compute/oslogin/service_account_ssh_test.py
>          out, _ = capsys.readouterr()
Instead of capturing output, have the function return a value/values, and test the returned value/values.

2023-06-13 12:40 UTC, kweinmeister approved these changes

2023-06-13 12:40 UTC, kweinmeister commented
@engelke @m-strzelczyk are we good to merge this now?

2023-06-13 15:10 UTC, m-strzelczyk commented
I think yes.

2023-06-20 10:05 UTC, rsamborski commented
> I think yes.

@m-strzelczyk There is [a comment](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10067#discussion_r1205957772) from @engelke to be addressed or at least agreed upon.

2023-06-20 16:06 UTC, m-strzelczyk commented
> > I think yes.
> 
> @m-strzelczyk There is [a comment](https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10067#discussion_r1205957772) from @engelke to be addressed or at least agreed upon.

This is resolved. I forgot to mark it.

2023-06-22 13:46 UTC, merged