feat(eventarc): audit log Event receiver sample
GoogleCloudPlatform/python-docs-samples pull request #10223
Opened 2023-06-12 21:57 UTC by muncus

## Description

Creates a new sample for receiving Audit Log CloudEvents from eventarc

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2023-06-14 17:57 UTC, muncus commented
The owlbot post-processor failure is unrelated to this PR (underlying error is a formatting issue with an appengine file not touched in this change).

2023-06-15 22:39 UTC, grayside requested changes
Thank you for putting together this PR. There's a couple aspects of this framed in questions below that we should clarify before proceeding.

2023-06-15 22:39 UTC, grayside commented on eventarc/auditlog_storage_handler/main.py
> +# [START eventarc_audit_cloudevent_handler]
I had expected something more like a narrow function than a full app. Should we narrow scope?

2023-06-15 22:39 UTC, grayside commented on eventarc/auditlog_storage_handler/main.py
> +# [START eventarc_audit_cloudevent_handler]
We had discussed changing scope on this to another product, should we hold off until that's been confirmed?

2024-06-17 04:45 UTC, closed without merging