fix: Update dualtoken.py
GoogleCloudPlatform/python-docs-samples pull request #10423
Opened 2023-07-13 16:06 UTC by msampathkumar

Minor Update.

Using `base64_encoder` instead of `urlsafe_b64encode`

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [x] Please **merge** this PR for me once it is approved

2023-07-13 16:42 UTC, justin-mp approved these changes

2023-07-17 16:06 UTC, rsamborski submitted a review, later dismissed
I have just noticed that `mediacdn_dualtoken_sign_path_component` region tag doesn't include any imports. Please make sure it's added it in the top (around line 17) to include imports used in that sample (base64, ed25519, datetime).

2023-08-03 16:02 UTC, msampathkumar commented
Update the PR. Included the imports in the region tags.

2023-08-03 19:20 UTC, dandhlee requested changes
Two pending failures (lint & test)

2023-08-03 19:20 UTC, dandhlee commented on media_cdn/dualtoken.py
> +    signature = base64.base64_encoder(digest).decode('utf-8')
`AttributeError: module 'base64' has no attribute 'base64_encoder'`

2023-08-03 19:20 UTC, dandhlee commented on media_cdn/dualtoken.py
> +# [END mediacdn_dualtoken_sign_path_component]
Can this be right below the import without a space? It will also help solve the lint issue.

2023-08-07 15:42 UTC, msampathkumar commented
Resolved the lint issues also updated the test file accordingly.

2023-08-28 11:24 UTC, m-strzelczyk approved these changes

2023-08-28 19:27 UTC, dandhlee approved these changes

2023-08-28 19:30 UTC, dandhlee commented
Dismissing @rsamborski's stale review, please feel free to re-raise it but looks good to me now.

2023-09-05 08:56 UTC, rsamborski approved these changes
Sorry for not looking at this for a while due to PTO. I am approving and merging it right now.

2023-09-05 08:57 UTC, merged