Vertex SDK - LLM - Added tuning samples for the `ChatModel` (`chat-bison`) and `CodeChatModel` (`codechat-bison`)
GoogleCloudPlatform/python-docs-samples pull request #10570
Opened 2023-08-29 06:20 UTC by Ark-kun

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2023-08-29 08:37 UTC, dandhlee requested changes
Reviewing for Python & sample style.

2023-08-29 08:37 UTC, dandhlee commented on generative_ai/tune_chat_model.py
> +        # Optional:
Remove unused comment.

2023-08-29 15:30 UTC, Ttris31 approved these changes

2023-08-29 19:59 UTC, Ark-kun commented
Thank you for the review. I'll try to implement the feedback.

I've tried to keep the samples consistent. These new samples are just copies of the existing samples created by the DPE team with model names changed. Perhaps the DPE team can initiate a repo-wide refactoring based on this feedback.

2023-11-21 11:45 UTC, msampathkumar commented on generative_ai/tune_chat_model.py
> +    # [END aiplatform_sdk_tune_code_chat_model]
```
    # [END aiplatform_sdk_tune_code_chat_model]
```

This does not match the start tag. Please check.

2024-06-17 04:46 UTC, closed without merging