Fix: [DLP] Mocked stored infotype related test cases to resolve #10556
GoogleCloudPlatform/python-docs-samples pull request #10593
Opened 2023-09-06 13:19 UTC by Avani-Thakker-Crest

## Description
This is a duplicate PR of #10567 (I have closed #10567 as CLA test was failing). Please re-review this one. Thank you!

Details:
Mocked stored Info type related test cases solving the revert request: #10556

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2023-09-06 14:02 UTC, annadata approved these changes

2023-09-07 10:38 UTC, rsamborski commented
@leahecole PTAL at this PR as you had comments in the original one (closed due to CLA issues)

2023-09-07 11:27 UTC, m-strzelczyk requested changes
Using mocks in tests comes with more responsibility for test authors to make sure the tested code does what it should.

You are mocking calls to the service you are aiming to demonstrate usage of. Make sure that you check if the sample code is in fact making calls that are valid. Currently, your tests allow for me to pass `None` as a request to the demonstrated methods - this should be caught.

2023-09-07 11:27 UTC, m-strzelczyk commented on dlp/snippets/stored_infotype_test.py
> +    )
There should be some assert to check if the mocked DLP Client was used at all. Something like `mock_dlp_instance.create_stored_info_type.assert_called_once()`.

You should also be inspecting if the method was called with the proper arguments (proper structure or the request). 

We lose a lot when switching from using real services to mocks. We should put additional effort to make sure we demonstrate proper usage of the libraries still. With mock like that, someone can mess up the API call and do `dlp.create_stored_info_type(request=None)` in the `dlp/snippets/stored_infotype.py` and the test would still pass.

2023-09-07 11:27 UTC, m-strzelczyk commented on dlp/snippets/stored_infotype_test.py
> +    assert stored_infotype_path in out
Please test if the mocked method was called with correct arguments.

2023-09-07 11:27 UTC, m-strzelczyk commented on dlp/snippets/stored_infotype_test.py
> +    assert "Quote: gary1998" in out
Please add checks to verify if the mocked method was called with correct arguments.

2023-09-07 14:30 UTC, leahecole commented
> @leahecole PTAL at this PR as you had comments in the original one (closed due to CLA issues)

My same comments about mocks still stand - they are against our authoring guide and given what @m-strzelczyk has raised about the concerns with the accuracy of these mocks I am going to re-open our conversation on chat about it

2023-09-11 17:54 UTC, Avani-Thakker commented
I am closing this PR since the one without the mocks works fine and the same PR is merged. PR with the issue fix, not using mocks:  https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10599

2023-09-11 17:54 UTC, closed without merging