migrate code from googleapis/python-videointelligence
GoogleCloudPlatform/python-docs-samples pull request #10605
Opened 2023-09-11 20:28 UTC by dizcology

migrate code from python-videointelligence

- Adds tutorials using Cloud Client [(#930)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/930)
- Adds new examples, replaces markdown with restructured text [(#945)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/945)
- Fix README rst links [(#962)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/962)
- updated the gcs files used in Usage [(#960)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/960)
- Updates examples for video [(#968)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/968)
- Fixes broken example in docs [(#987)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/987)
- Places format calls inside print function calls. [(#995)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/995)
- Auto-update dependencies. [(#1093)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1093)
- Update all generated readme auth instructions [(#1121)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1121)
- Auto-update dependencies. [(#1123)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1123)
- Video v1beta2 [(#1088)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1088)
- Added Link to Python Setup Guide [(#1158)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1158)
- Auto-update dependencies. [(#1186)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1186)
- update samples to v1 [(#1221)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1221)
- Do not base64 encode the input content. [(#1241)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1241)
- remove empty input_uri [(#1244)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1244)
- Disable another FACE_DETECTION test [(#1253)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1253)
- Added "Open in Cloud Shell" buttons to README files [(#1254)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1254)
- Auto-update dependencies. [(#1377)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1377)
- Remove video face [(#1348)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1348)
- Face detection beta features [(#1414)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1414)
- [DO NOT MERGE] remove face detection samples [(#1435)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1435)
- Regenerate the README files and fix the Open in Cloud Shell link for some samples [(#1441)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1441)
- update client library version [(#1442)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1442)
- Update READMEs to fix numbering and add git clone [(#1464)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1464)
- Add video region tags [(#1489)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1489)
- Add automatic punctuation to video speech transcription [(#1603)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1603)
- Video Intelligence region tag update [(#1639)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1639)
- Use explicit URIs for Video Intelligence sample tests [(#1743)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1743)
- Access Display Names of enum fields via enum object [(#1738)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1738)
- Add beta snippets for object tracking / text detection [(#1773)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1773)
- more info on alternatives [(#1791)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1791)
- feat: video speech transcription [(#1849)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1849)
- Lib version update for Video Intelligence API [(#1850)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1850)
- Video: edit region tag [(#1851)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1851)
- Auto-update dependencies. [(#1980)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1980)
- Video GA text detection and object tracking [(#2024)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2024)
- add video streaming samples [(#2047)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2047)
- Wait longer for sometimes slow operation [(#2056)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2056)
- Fix urllib2 [(#2059)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2059)
- replace demomaker with cloud-samples-data/video for video intelligenc… [(#2162)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2162)
- fix python2 print unicode issue [(#2183)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2183)
- explicitly set timeout in steaming_annotate_video, and comment [(#2182)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2182)
- update streaming samples [(#2215)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2215)
- [video] Streaming AutoML Classification [(#2313)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2313)
- Use video_path fixture [(#2363)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2363)
- Adds updates for samples profiler ... vision [(#2439)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2439)
- Auto-update dependencies. [(#2005)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2005)
- video: add auto-generated Logo Recognition Samples [(#2755)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2755)
- video: adding face detection and person detection samples for beta [(#2919)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2919)
- chore(deps): update dependency google-cloud-storage to v1.26.0 [(#3046)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3046)
- fix: wait up to 20 seconds for blob to appear [(#3061)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3061)
- Update analyze.py [(#3088)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3088)
- video: adding GA samples for logo detection [(#3098)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3098)
- Simplify noxfile setup. [(#2806)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2806)
- video: fix flaky beta tests [(#3235)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3235)
- video: use flaky on flaky timeouts [(#3385)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3385)
- vision: delete obsolete beta snippets for logo detection  [(#3114)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3114)
- [video] testing: mark some tests witih flaky [(#3446)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3446)
- chore(deps): update dependency google-cloud-storage to v1.28.0 [(#3260)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3260)
- chore: some lint fixes [(#3751)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3751)
- chore(deps): update dependency google-cloud-storage to v1.28.1 [(#3785)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3785)
- testing: start using btlr [(#3959)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/3959)
- fix: changes positional to named pararameters in Video samples [(#4017)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/4017)
- Replace GCLOUD_PROJECT with GOOGLE_CLOUD_PROJECT. [(#4022)](https://github.com/GoogleCloudPlatform/python-docs-sampl [...]

2023-09-12 09:01 UTC, rsamborski requested changes
Thank you for the code migration. Before merging please update:
 - [CODEOWNERs](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS)
 - [Blunderbuss](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml)

Couple additional notes to remember:
 - CLA issues will require admin merge
 - Remember to use `merge` instead of `squash and merge` to keep history intact

2023-09-12 16:08 UTC, dizcology commented on videointelligence/samples/analyze/analyze_test.py
> +@pytest.mark.slow
Removed all `@pytest.mark.slow`.

2023-09-12 16:08 UTC, dizcology commented
CODEOWNERS and blunderbuss updated.

2023-09-12 19:50 UTC, rsamborski approved these changes

2023-09-15 16:57 UTC, leahecole approved these changes

2023-09-15 16:58 UTC, leahecole commented
CLA is okay, these are xooglers

2023-09-15 16:59 UTC, merged