feat: add sample and test for getting an access token from an imperso…
GoogleCloudPlatform/python-docs-samples pull request #10759
Opened 2023-10-11 22:12 UTC by irataxy

…nated SA

## Description

Fixes b:302748677
- [X] Please **merge** this PR for me once it is approved

2023-10-12 01:47 UTC, arithmetic1728 approved these changes

2023-10-12 01:50 UTC, arithmetic1728 requested changes
LGTM for snippets.py. However, the snippets_test.py failed due to:

```
google.auth.exceptions.RefreshError: ('Unable to acquire impersonated credentials', '{\n  "error": {\n    "code": 404,\n    "message": "Not found; Gaia id not found for email [sa@project.service.gserviceaccount.com](mailto:sa@project.service.gserviceaccount.com)",\n    "status": "NOT_FOUND"\n  }\n}\n')
```

2023-10-12 20:35 UTC, Sita04 commented
@GoogleCloudPlatform/python-samples-reviewers 
Kindly help set up a similar CL: 572924785 testing resource.

2023-10-13 09:45 UTC, rsamborski approved these changes
Access will be granted per cl/573156138

2023-10-13 09:45 UTC, rsamborski commented on auth/cloud-client/snippets_test.py
> +    impersonated_service_account = "sa@project.service.gserviceaccount.com"
Please use `auth-samples-testing@python-docs-samples-tests.iam.gserviceaccount.com`

2023-10-13 15:39 UTC, irataxy commented on auth/cloud-client/snippets_test.py
> +    impersonated_service_account = "sa@project.service.gserviceaccount.com"
Done

2023-10-13 19:18 UTC, arithmetic1728 commented
test is still failing for the same reason

2023-10-16 11:40 UTC, rsamborski commented
> test is still failing for the same reason

Fixed with cl/573772247

2023-10-16 17:52 UTC, arithmetic1728 approved these changes

2023-10-16 17:52 UTC, merged