Outdated bash operator import on Composer 2 Docs #11433
GoogleCloudPlatform/python-docs-samples pull request #11440
Opened 2024-04-12 09:38 UTC by magar51

## Description

Fixes #11433 

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2024-04-12 15:25 UTC, holtskinner approved these changes

2024-04-18 16:03 UTC, leahecole requested changes
I left some comments - there are places where the BashOperator should not be modified. Additionally, please revert the changes in the `endpoint` and `speech` directories and submit them as separate PRs with linked issues. Additionally, I changed it to be a Draft PR while lint and tests are not passing. Feel free to change it back to "ready to review" once they are passing!

2024-04-23 14:36 UTC, leahecole commented on endpoints/getting-started/main.py
> +    """Retrieves the authentication information from Google Cloud Endpoints."""
```suggestion
    """Retrieves the authenication information from Google Cloud Endpoints."""
```
removing because this is fixed in #11332

2024-04-23 14:37 UTC, leahecole commented on endpoints/getting-started/main.py
> +    logging.exception("An error occurred while processing the request.")
```suggestion
    logging.exception("An error occured while processing the request.")
```

Removing because this is fixed in #11332

2024-04-23 14:38 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +from google.cloud.speech_v2 import AutoDetectDecodingConfig
```suggestion
from google.cloud.speech_v2 import cloud_speech as cloud_speech_types
```

2024-04-23 14:38 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +from google.cloud.speech_v2 import AutoDetectDecodingConfig
```suggestion
from google.cloud.speech_v2 import cloud_speech as cloud_speech_types
```

2024-04-23 14:39 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +        StreamingRecognizeRequest(audio=audio) for audio in stream
```suggestion
       cloud_speech_types.StreamingRecognizeRequest(audio=audio) for audio in stream
```

2024-04-23 14:40 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +        StreamingRecognizeRequest(audio=audio) for audio in stream
```suggestion
        cloud_speech_types.StreamingRecognizeRequest(audio=audio) for audio in stream
```

2024-04-23 14:40 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +        auto_decoding_config=AutoDetectDecodingConfig(),
```suggestion
    recognition_config = cloud_speech_types.RecognitionConfig(
        auto_decoding_config=cloud_speech_types.AutoDetectDecodingConfig(),
```

2024-04-23 14:40 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +    streaming_config = StreamingRecognitionConfig(
```suggestion
    streaming_config = cloud_speech_types.StreamingRecognitionConfig(
```

2024-04-23 14:40 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +    config_request = StreamingRecognizeRequest(
```suggestion
    config_request = cloud_speech_types.StreamingRecognizeRequest(
```

2024-04-23 14:41 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +    def requests(config: RecognitionConfig, audio: list) -> list:
```suggestion
    def requests(config: cloud_speech_types.RecognitionConfig, audio: list) -> list:
```

2024-04-23 14:43 UTC, leahecole commented on speech/snippets/transcribe_streaming_v2.py
> +from google.cloud.speech_v2 import cloud_speech as cloud_speech_types
```suggestion
from google.cloud.speech_v2.types import cloud_speech as cloud_speech_types
```

2024-04-23 16:25 UTC, leahecole approved these changes

2024-04-23 16:25 UTC, merged