Update generate_self_signed_jwt.py
GoogleCloudPlatform/python-docs-samples pull request #12592
Opened 2024-09-13 20:30 UTC by riathakkar

This is a bug fix in response to a listener report. The datetime object needs to return the current time in epoch

## Description

Fixes b/366503744

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [X ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [X] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [X] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [X] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [X ] Please **merge** this PR for me once it is approved

2024-09-14 05:01 UTC, iennae requested changes
I dug into this since it to better understand what is happening here. 

Based on https://cloud.google.com/iam/docs/reference/credentials/rest/v1/projects.serviceAccounts/signJwt it seems like the required context is 

string

Required. The JWT payload to sign. Must be a serialized JSON object that contains a JWT Claims Set. For example: {"sub": "user@example.com", "iat": 313435}

If the JWT Claims Set contains an expiration time (exp) claim, it must be an integer timestamp that is not in the past and no more than 12 hours in the future.

So then I looked at what would a valid claims set look like. 

IAT - "This is a timestamp formatted as whole seconds since January 01, 1970, which is a standard UNIX representation of time. The timestamp must be an integer (no decimals) and it must be in UTC."

I checked to see whether your code would work: 

>>> iat=datetime.datetime.now(tz=datetime.timezone.utc).timestamp
>>> exp = iat + 3600
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'builtin_function_or_method' and 'int'
 
 
 I suspect what is needed is something like 
 
 now_utc = datetime.datetime.now(tz=datetime.timezone.utc)
 iat = int(now_utc.timestamp())
 
 Which I checked : 
 >>> now_utc = datetime.datetime.now(tz=datetime.timezone.utc)
>>> iat = int(now_utc.timestamp())
>>> iat
1726289956 

it's helpful to share a reference to the bug with a b/ which might provide additional context I don't have here. 

Finally, I think a test might be missing here if we're not catching this

2024-09-16 16:19 UTC, riathakkar commented
Thanks for the catch. Did something silly when copying this over. I think tests would be helpful, but it would be a non trivial effort to do so. Id love to pick it up as another task and get the code sample fixed now for our customers.

2024-09-18 17:51 UTC, iennae commented
@riathakkar can you update the code so that it works using time or int()?

2024-09-19 20:14 UTC, iennae approved these changes

2024-09-20 00:19 UTC, merged