refactor: (GenAI) Reorganized Token Count Samples (Group C)
GoogleCloudPlatform/python-docs-samples pull request #12616
Opened 2024-09-20 15:27 UTC by Thoughtseize1

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample
- [ ] This sample adds a new **Product API**, and I updated the [Blunderbuss issue/PR auto-assigner](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml) with the codeowners for this sample
- [ ] Please **merge** this PR for me once it is approved

2024-09-20 15:53 UTC, holtskinner requested changes

2024-09-20 15:53 UTC, holtskinner commented on generative_ai/token_count/simple_example.py
Do we need this example in addition to the `api_example.py`? They seem to accomplish the same task

2024-09-25 16:13 UTC, msampathkumar commented on generative_ai/token_count/multimodal_token_count_example.py
> +    model = GenerativeModel("gemini-1.5-flash-001")
```suggestion
    model = GenerativeModel("gemini-1.5-flash-002")
```

2024-09-25 16:14 UTC, msampathkumar commented on generative_ai/token_count/simple_example.py
> +    model = GenerativeModel("gemini-1.5-flash-001")
```suggestion
    model = GenerativeModel("gemini-1.5-flash-002")
```

2024-09-25 16:15 UTC, msampathkumar commented on generative_ai/token_count/simple_example.py
Once the sample are segregated into individual folders, it might easier to find and fix duplicates.

2024-09-25 17:04 UTC, msampathkumar approved these changes
LGTM

2024-09-26 10:50 UTC, merged

2024-09-26 10:52 UTC, msampathkumar commented
Holt's query is valid, but its outside the scope of this reorganization effort. The CICD for GenAI samples is taking too long due to duplicated code, so we're prioritizing a fast-paced approach to this reorganization.