FIXED encoding issue
GoogleCloudPlatform/python-docs-samples pull request #4637
Opened 2020-09-05 19:21 UTC by Manoj-nathwani

- `policy["policy"]` type is `bytes` so we need to decode it to make it a valid `str`
- Otherwise it kinda look like `<input name='policy' value='b'aaaaaaa'' type='hidden'/>\n` which is is processed as `value='b'` when posting the html form
- I'm adding a generic if on `type(value)` though, just in-case there's future updates to other fields which also need fixing

2020-09-05 19:48 UTC, Manoj-nathwani commented
@googlebot I signed it!

2020-09-22 20:56 UTC, dinagraves requested changes

2020-09-22 20:56 UTC, dinagraves commented on storage/cloud-client/storage_generate_signed_post_policy_v4.py
> +        if type(value) == bytes: value = value.decode("utf-8")
Thank you for the PR!  Can you add a newline here?  ie:

```
if {condition}:
    code is on new line 
```

2020-09-28 18:47 UTC, closed without merging

2020-09-28 20:46 UTC, Manoj-nathwani commented on storage/cloud-client/storage_generate_signed_post_policy_v4.py
> +            value = value.decode("utf-8")
Sure