Functions: add comment
GoogleCloudPlatform/python-docs-samples pull request #4797
Opened 2020-10-05 19:24 UTC by anguillanneuf

Fixes #4671 

Users get confused by when a push message that triggers a function is ack'ed, despite [docs](https://cloud.google.com/functions/docs/calling/pubsub).

> Cloud Functions acks the message internally upon successful function invocation.

This comment helps clear this confusion. Even if the function subsequently fails to publish (any message, not limited to the push message that triggered the function), the original push message that triggered the function is ack'ed.

2020-10-05 20:20 UTC, busunkim96 approved these changes

2020-10-05 20:24 UTC, grant commented
Thanks for the PR.

I don't believe this suggested change will address the users's issue. Every function is invoked in every function sample, so we don't need to state that we invoked the function. If we made this change, we would also need to change all of our samples like Java and Node which use the same log statement.

Rather, I think a change to the docs would clarify and address the non-language-specific issue. Or a different comment than the changed one in this PR.

2020-10-05 20:24 UTC, grant requested changes
Thanks for the PR.

I don't believe this suggested change will address the users's issue. Every function is invoked in every function sample, so we don't need to state that we invoked the function. If we made this change, we would also need to change all of our samples like Java and Node which use the same log statement.

Rather, I think a change to the docs would clarify and address the non-language-specific issue. Or a different comment than the changed one in this PR.

2020-10-05 21:51 UTC, anguillanneuf commented
That sounds good to me. I can close this PR after the internal CL is submitted. Thanks!

2020-10-19 18:09 UTC, engelke approved these changes

2020-10-19 20:02 UTC, ace-n commented on functions/pubsub/main.py
> +    print(f'Function is invoked. Next, publish message to topic {topic_name}')
Nit:
> Function **was** invoked. **Now publishing** message to topic ...

2020-11-17 20:38 UTC, leahecole commented
@anguillanneuf I'm going to close this because the internal CL looks like it's submitted - please reopen if needed.

2020-11-17 20:38 UTC, closed without merging