adding function that will stop instances!
GoogleCloudPlatform/python-docs-samples pull request #4909
Opened 2020-10-26 12:59 UTC by theadisoni

function that will fetch all running instances and will stop them , project_id and instance action be hard coded or take input from user itself!, it will be great help for people who  new to use api call for GCP

## Description

Fixes #<ISSUE-NUMBER>

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

2020-10-26 20:50 UTC, leahecole commented
Hey @theadisoni ! Thanks for your contribution - I'm going to ask someone more familiar with the Compute Engine SDK than I am to take a look at your sample, but in the meantime, a couple of requests:
1) Please sign the CLA (instructions in the comment from our trusty CLA bot above)
2) Please include a system test for the sample you're adding - take a look at our [Testing guidelines](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#testing-guidelines) for the testing standards, and at some of the other [compute examples](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/compute) to see what tests look like. 

A quick note on running tests yourself - our CI/CD will need to be kicked off by someone in our GitHub org (I'll do my best to keep an eye on it) but to run things locally, take a look at the [test environment setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup)

2020-10-28 18:10 UTC, leahecole commented
adding the do not merge label for now until tests are added and more discussion can occur

2020-11-04 20:19 UTC, engelke requested changes
Thanks for the PR! Please accept the contributor license agreement, or we will not be able to merge it.

2020-11-05 03:02 UTC, theadisoni commented
@googlebot I signed it!
Hi @engelke @leahecole **i have already signed the CLA** on 26th Oct itself, please verify it again! and please let me know other changes if any! 
Thanks

2020-11-05 23:28 UTC, leahecole commented
Thanks for signing the CLA! The other big change we'd need is the addition of a test - 

Please include a system test for the sample you're adding - take a look at our [Testing guidelines](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#testing-guidelines) for the testing standards, and at some of the other [compute examples](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/compute) to see what tests look like. 

A quick note on running tests yourself - our CI/CD will need to be kicked off by someone in our GitHub org (I'll do my best to keep an eye on it) but to run things locally, take a look at the [test environment setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup)

2020-11-07 16:00 UTC, theadisoni commented
Hi @leahecole , This is my first contribution towards GoogleCloudPlatform for api so need some time to understand test cases and how to submit them I will try my best to understand and submit ASAP, Can you please help me with it, or recommend any previous submission from there I can take help for same!.
Thanks.

2020-11-11 18:05 UTC, leahecole commented
@theadisoni - the links from above include links to our testing guidelines, instructions for setting up a test environment, and links to other relevant tests. 



>  Please include a system test for the sample you're adding - take a look at our [Testing guidelines](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#testing-guidelines) for the testing standards, and at some of the other [compute examples](https://github.com/GoogleCloudPlatform/python-docs-samples/tree/master/compute) to see what tests look like. 
>
> A quick note on running tests yourself - our CI/CD will need to be kicked off by someone in our GitHub org (I'll do my best to keep an eye on it) but to run things locally, take a look at the [test environment setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup)

2020-12-14 19:32 UTC, leahecole commented
Closing for now, feel free to reopen if you continue to work on it.

2020-12-14 19:32 UTC, closed without merging