docs: fix simple typo, tempaltes -> templates
GoogleCloudPlatform/python-docs-samples pull request #5188
Opened 2020-12-24 06:26 UTC by timgates42

There is a small typo in appengine/standard/i18n/README.md.

Should read `templates` rather than `tempaltes`.

Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

2020-12-28 18:22 UTC, leahecole approved these changes

2020-12-28 18:23 UTC, leahecole requested changes

2020-12-28 18:23 UTC, leahecole commented on appengine/standard/i18n/README.md
> +Jija2 templates.
Hey @timgates42 ! Thanks for this contribution! It looks like there's actually a second typo - would you be willing to add the correction for Jinja2 as well please? 
```suggestion
Jinja2 templates.
```

2020-12-30 20:08 UTC, timgates42 commented
Thanks @leahecole

2021-01-07 16:29 UTC, busunkim96 approved these changes

2021-01-12 18:33 UTC, leahecole approved these changes

2021-01-12 18:40 UTC, merged