healthcare API: formatting fixes and cleanup
GoogleCloudPlatform/python-docs-samples pull request #5691
Opened 2021-04-13 22:03 UTC by noerog

## Description

Beginning of fixes for:

b/183816408
b/158653137
b/159065286

## Checklist
- [X] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [X] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [X] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [X] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [X] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

2021-04-13 22:17 UTC, noerog commented
@dandhlee What is wrong with the license header?

2021-04-13 22:36 UTC, dandhlee commented
the header-check bot unfortunately only recognizes one year format, and not multiple years.
If you reduce from `Copyright 2018, 2019, 2020 Google LLC All Rights Reserved.` to just `Copyright 2018 Google LLC All Rights Reserved.` it should make the header-check bot happy.

2021-04-13 23:12 UTC, dandhlee requested changes

2021-04-14 15:46 UTC, noerog commented on healthcare/api-client/v1/datasets/datasets_test.py
>  import datasets
Done.

2021-04-14 15:56 UTC, noerog commented on healthcare/api-client/v1/datasets/README.rst
> +                            samples/healthcare/api-client/v1/datasets before
Done.

2021-04-14 16:25 UTC, dandhlee approved these changes
LGTM.

2021-04-21 17:29 UTC, noerog commented
Ping @tmatsuo

2021-04-21 21:51 UTC, tmatsuo approved these changes

2021-04-21 23:16 UTC, merged