chore: Updating list of documents
GoogleCloudPlatform/python-docs-samples pull request #6162
Opened 2021-06-17 12:04 UTC by m-strzelczyk

Adding a new link to README pointing to documentation that uses samples from this folder.

## Description

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

2021-06-17 19:51 UTC, dandhlee requested changes
Thanks for the update! Please see comments below :)

2021-06-17 19:51 UTC, dandhlee commented on compute/metadata/README.md
>  > https://cloud.google.com/compute/docs/metadata
Could you update this link? It redirects to `https://cloud.google.com/compute/docs/storing-retrieving-metadata` which I think it still redirects to the link you want but let's update the original link as well.

2021-06-17 19:51 UTC, dandhlee commented on compute/metadata/README.md
> +> https://cloud.google.com/compute/docs/instances/verifying-instance-identity
The two links show up side by side, could you fix the formatting? Reference: https://cloud.google.com/compute/docs/storing-retrieving-metadata

2021-06-18 14:47 UTC, dandhlee approved these changes
LGTM.

2021-06-18 17:54 UTC, engelke approved these changes

2021-06-18 18:03 UTC, merged