[@wescpy] make GAE Quickstart samples consistent
GoogleCloudPlatform/python-docs-samples pull request #6710
Opened 2021-09-18 02:18 UTC by wescpy

These samples should be nearly identical (except for `app.yaml`). They've been edited by different engineers over the years and have drifted slightly apart. This PR aims to put them in-sync again. A pair of bugs were filed (within Google), and this PR will be linked to them as the fix.

2021-09-18 16:30 UTC, dandhlee requested changes

2021-09-18 16:30 UTC, dandhlee commented on appengine/flexible/hello_world/main.py
> +# Copyright 2021 Google LLC
Please leave the copyright year as-is!

2021-09-18 16:30 UTC, dandhlee commented on appengine/standard_python3/hello_world/main.py
> +# Copyright 2021 Google LLC
Ditto.

2021-09-20 16:31 UTC, wescpy commented
reverted copyright years

2021-09-20 16:32 UTC, wescpy commented on appengine/flexible/hello_world/main.py
> +# Copyright 2021 Google LLC
DONE

2021-09-20 16:32 UTC, wescpy commented on appengine/standard_python3/hello_world/main.py
> +# Copyright 2021 Google LLC
DONE

2021-09-20 16:38 UTC, dandhlee approved these changes
LGTM.

2021-09-20 18:36 UTC, leahecole approved these changes

2021-09-20 19:28 UTC, merged

2021-09-20 22:59 UTC, wescpy commented
thx all!