Add kokoro 3.10 configs as an optional check
GoogleCloudPlatform/python-docs-samples pull request #6728
Opened 2021-09-24 17:13 UTC by leahecole

## Description

Fixes #<ISSUE-NUMBER>

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/.github/CODEOWNERS) with the codeowners for this sample

2021-09-24 22:23 UTC, dandhlee requested changes
Yay 3.10!

2021-09-24 22:23 UTC, dandhlee commented on .kokoro/python3.10/common.cfg
> +# Copyright 2019 Google LLC
```suggestion
# Copyright 2021 Google LLC
```

2021-09-24 22:23 UTC, dandhlee commented on .kokoro/python3.10/continuous.cfg
> +# Copyright 2020 Google LLC
```suggestion
# Copyright 2021 Google LLC
```

2021-09-24 22:23 UTC, dandhlee commented on .kokoro/python3.10/periodic.cfg
> +# Copyright 2020 Google LLC
```suggestion
# Copyright 2021 Google LLC
```

2021-09-24 22:23 UTC, dandhlee commented on .kokoro/python3.10/presubmit.cfg
> +# Copyright 2019 Google LLC
```suggestion
# Copyright 2021 Google LLC
```

2021-09-24 22:23 UTC, dandhlee commented on appengine/standard/noxfile-template.py
>  ALL_VERSIONS = ["2.7", "3.6", "3.7", "3.8", "3.9"]
Should we also include "3.10" in here?

2021-09-27 18:30 UTC, leahecole commented on appengine/standard/noxfile-template.py
>  ALL_VERSIONS = ["2.7", "3.6", "3.7", "3.8", "3.9"]
```suggestion
ALL_VERSIONS = ["2.7", "3.6", "3.7", "3.8", "3.9", "3.10"]
```

2021-09-27 18:33 UTC, dandhlee approved these changes
LGTM!

2021-09-27 19:04 UTC, nicain approved these changes

2021-09-27 19:04 UTC, merged