Fix airflow_db_cleanup script
GoogleCloudPlatform/python-docs-samples pull request #7593
Opened 2022-03-15 00:15 UTC by khokharnikunj8

## Description

Fixes b/223364117 

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2022-03-15 05:58 UTC, dandhlee requested changes
Reviewing for sample reviewers. Please fix the lint error as well.

2022-03-15 05:58 UTC, dandhlee commented on composer/airflow_1_samples/airflow_db_cleanup.py
> +                    context["params"].get("do_not_delete_by_dag_id")):
This can be simplified to `if context["params"].get("do_not_delete_by_dag_id"):` assuming that it retrieves the boolean value.

2022-03-17 17:04 UTC, khokharnikunj8 commented
> Please give python-samples-reviewers@ access to the doc with context.
> 
> Also, does this affect only Airflow 1, or do we need to make these changes in https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/composer/workflows/airflow_db_cleanup.py as well?

Hi, Currently we aim to fix the script for Airflow version 1. We will soon update the script for Airflow version 2 in the later phases. 

Gave access to the document to python-samples-reviewers@.

Thanks!

2022-03-17 17:06 UTC, khokharnikunj8 commented on composer/airflow_1_samples/airflow_db_cleanup.py
> +                    query.filter(age_check_column <= max_date,).filter(airflow_db_model.dag_id == dag).delete(synchronize_session=False)
No. Removed extra comma. Thanks!

2022-03-17 22:01 UTC, leahecole approved these changes
If @dandhlee 's concerns are addressed, LGTM

2022-03-17 22:05 UTC, dandhlee requested changes
One last edit!

2022-03-17 22:05 UTC, dandhlee commented on composer/airflow_1_samples/airflow_db_cleanup.py
> +                query.filter(age_check_column <= max_date,).delete(synchronize_session=False)
```suggestion
                query.filter(age_check_column <= max_date).delete(synchronize_session=False)
```

2022-03-21 11:37 UTC, dandhlee approved these changes
LGTM!

2022-03-21 23:56 UTC, merged