dataflow/custom-containers: add readmes and support cli options
GoogleCloudPlatform/python-docs-samples pull request #7601
Opened 2022-03-15 19:46 UTC by davidcavazos

## Description

This makes the following changes to the Dataflow custom container samples:
* Adds a README file with instructions on how to run
* Supports command line arguments on the pipelines
* Update to Python 3.9
* Update to Beam 2.37

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2022-03-15 21:01 UTC, dandhlee requested changes

2022-03-15 21:53 UTC, davidcavazos commented on dataflow/custom-containers/miniconda/e2e_test.py
> -    subprocess.check_call(
Thanks, removed!

2022-03-15 21:53 UTC, davidcavazos commented on dataflow/custom-containers/miniconda/e2e_test.py
> +            "_JOB_NAME": utils.hyphen_name(NAME),
Adding to requirements-test.txt

2022-03-16 00:46 UTC, dandhlee commented
Getting the following error now:
```
Traceback (most recent call last):
  File "/workspace/dataflow/custom-containers/miniconda/e2e_test.py", line 54, in test_tensorflow_minimal
    job_id = utils.dataflow_job_id(utils.hyphen_name(NAME))
  File "/workspace/dataflow/conftest.py", line 339, in dataflow_job_id
    raise ValueError(f"Dataflow job not found: job_name={job_name}")
ValueError: Dataflow job not found: job_name=dataflow-custom-containers-miniconda-py39-c49859
```

2022-03-16 22:06 UTC, dandhlee approved these changes
Yay! LGTM.

2022-03-24 22:02 UTC, engelke approved these changes

2022-03-25 17:11 UTC, merged