chore: update authoring guide with nox testing note
GoogleCloudPlatform/python-docs-samples pull request #7781
Opened 2022-04-11 13:32 UTC by dandhlee

## Description

Adding a note to indicate that tests will only run for where the `noxfile_config.py` file is, and for any tests that conform to the style that Noxfile is looking for. 

Fixes #7780.

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] Please **merge** this PR for me once it is approved.

2022-04-11 15:29 UTC, m-strzelczyk requested changes

2022-04-11 16:06 UTC, dandhlee commented on AUTHORING_GUIDE.md
> +ℹ️ **Note:** Nox only detects tests in the directory where the `noxfile_config.py` file is, [for any files named `*_test.py` or `test_*.py`](https://github.com/GoogleCloudPlatform/python-docs-samples
Ah, oops, linked it myself and looked it over 🤪. Updated!

2022-04-11 16:06 UTC, dandhlee commented
Thank you! Please take a look again.

2022-04-13 15:58 UTC, m-strzelczyk approved these changes

2022-06-02 14:38 UTC, leahecole approved these changes

2022-06-02 14:44 UTC, merged