adding owlbot and notebook ci
GoogleCloudPlatform/python-docs-samples pull request #7810
Opened 2022-04-21 01:02 UTC by loferris

## Description

Fixes #7809

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [x] Please **merge** this PR for me once it is approved.

2022-04-22 00:51 UTC, parthea approved these changes

2022-04-22 00:54 UTC, parthea requested changes
Need to check why owl bot is deleting `.github/snippet-bot.yml`

2022-04-22 00:54 UTC, parthea commented on .github/snippet-bot.yml
> -  - README.md
I don't think this file should be deleted.

2022-05-04 10:46 UTC, parthea approved these changes

2022-05-04 10:48 UTC, parthea requested changes
The `header-check` is failing with this message 
```
.cloud-build/CheckPythonVersion.py should have a copyright year of 2022
.cloud-build/cleanup/cleanup-cloudbuild.yaml is missing a valid license header.
.cloud-build/cleanup/requirements.txt is missing a valid license header.
.cloud-build/execute_changed_notebooks_cli.py should have a copyright year of 2022
.cloud-build/execute_notebook_cli.py should have a copyright year of 2022
.cloud-build/execute_notebook_helper.py should have a copyright year of 2022
.cloud-build/execute_notebook_remote.py should have a copyright year of 2022
.cloud-build/notebook-execution-test-cloudbuild-single.yaml is missing a valid license header.
.cloud-build/notebook-execution-test-cloudbuild.yaml is missing a valid license header.
.cloud-build/requirements.txt is missing a valid license header.
.cloud-build/test_folders.txt is missing a valid license header.
.cloud-build/utils/__init__.py is missing a valid license header.
.github/workflows/ci.yaml is missing a valid license header.
.github/workflows/linter/requirements.txt is missing a valid license header.
.github/workflows/linter/run_linter.sh should have a copyright year of 2022
```

2022-09-23 21:56 UTC, dandhlee commented
Hey @loferris, friendly ping on this!

2023-02-02 22:02 UTC, loferris commented
> The `header-check` is failing with this message
> 
> ```
> .cloud-build/CheckPythonVersion.py should have a copyright year of 2022
> .cloud-build/cleanup/cleanup-cloudbuild.yaml is missing a valid license header.
> .cloud-build/cleanup/requirements.txt is missing a valid license header.
> .cloud-build/execute_changed_notebooks_cli.py should have a copyright year of 2022
> .cloud-build/execute_notebook_cli.py should have a copyright year of 2022
> .cloud-build/execute_notebook_helper.py should have a copyright year of 2022
> .cloud-build/execute_notebook_remote.py should have a copyright year of 2022
> .cloud-build/notebook-execution-test-cloudbuild-single.yaml is missing a valid license header.
> .cloud-build/notebook-execution-test-cloudbuild.yaml is missing a valid license header.
> .cloud-build/requirements.txt is missing a valid license header.
> .cloud-build/test_folders.txt is missing a valid license header.
> .cloud-build/utils/__init__.py is missing a valid license header.
> .github/workflows/ci.yaml is missing a valid license header.
> .github/workflows/linter/requirements.txt is missing a valid license header.
> .github/workflows/linter/run_linter.sh should have a copyright year of 2022
> ```

Cannot be fixed manually on this PR, as the headers are missing in the synthtool template, so owlbot overwrites.

2023-05-26 19:41 UTC, kweinmeister commented
Closing this PR, as #10011 will supersede it.

2023-05-26 19:41 UTC, closed without merging