Added DAG file for Airflow Summit 2022
GoogleCloudPlatform/python-docs-samples pull request #7877
Opened 2022-05-09 14:21 UTC by PeWu

## Description

Added DAG file for Airflow Summit 2022.

The DAG will showcase autoscaling in Cloud Composer.

## Checklist
- [X] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [X] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [X] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [X] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2022-05-10 07:11 UTC, dandhlee commented
Handing off to Leah, our Composer expert!

2022-05-13 20:34 UTC, leahecole requested changes
Slight nit otherwise LGTM @PeWu !! Sorry for delay in review

2022-05-13 20:34 UTC, leahecole commented on composer/2022_airflow_summit/README.md
> +Running a number of tasks in parallel showcases autoscaling in a Cloud Composer environment.
```suggestion
# Airflow Summit 2022 Sample DAGs

DAGs in this directory are part of the curriculum for the [Cloud Composer Workshop](https://airflowsummit.org/sessions/2022/cloud-composer-workshop/) at the 2022 Airflow summit. Be sure to [register](https://ti.to/airflowsummit/2022-workshops) and join us there!  

## parallel_work

Running a number of tasks in parallel showcases autoscaling in a Cloud Composer environment.
```

2022-05-13 21:26 UTC, leahecole reviewed
Oh! Also! Please add a `requirements.txt` file that has Airflow in it and any other dependencies needed (I don't think you'll need any)
and a `requirements-test.txt` file that is identical to [this one](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/composer/workflows/requirements-test.txt)

2022-05-16 09:06 UTC, PeWu commented on composer/2022_airflow_summit/README.md
> +Running a number of tasks in parallel showcases autoscaling in a Cloud Composer environment.
Done

2022-05-16 09:07 UTC, PeWu commented
> Oh! Also! Please add a `requirements.txt` file that has Airflow in it and any other dependencies needed (I don't think you'll need any) and a `requirements-test.txt` file that is identical to [this one](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/composer/workflows/requirements-test.txt)

Done

2022-05-16 14:05 UTC, leahecole approved these changes

2022-05-16 14:30 UTC, parthea approved these changes

2022-05-16 14:32 UTC, merged