Update comment about variables
GoogleCloudPlatform/python-docs-samples pull request #7881
Opened 2022-05-11 07:04 UTC by jsj14

## Description

Fixes #<ISSUE-NUMBER>

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2022-05-11 13:57 UTC, dandhlee requested changes
Could you also be able to rebase/squash the 46 commits?

2022-05-11 14:42 UTC, leahecole requested changes
LGTM after small changes are resolved

2022-05-11 14:42 UTC, leahecole commented on composer/workflows/dataproc_batch_operators.py
>  TODO: Add the tutorial link once it is published.
We know it will be https://cloud.google.com/composer/docs/composer-2/run-dataproc-workloads but that link won't work yet

2022-05-11 14:42 UTC, leahecole commented on composer/workflows/dataproc_batch_operators.py
> +* project_id is the Project ID.
+1 - the previous version was clearer

2022-05-12 15:25 UTC, jsj14 commented on composer/workflows/dataproc_batch_operators.py
>  TODO: Add the tutorial link once it is published.
Do I add the link regardless now itself? or do it later with issue #7803

2022-05-13 13:34 UTC, leahecole commented on composer/workflows/dataproc_batch_operators.py
>  TODO: Add the tutorial link once it is published.
@dandhlee are you okay with us waiting given that we have an issue open to add the link?

2022-05-13 13:48 UTC, dandhlee commented on composer/workflows/dataproc_batch_operators.py
>  TODO: Add the tutorial link once it is published.
SGTM!

2022-05-17 04:30 UTC, jsj14 commented
@dandhlee  @leahecole can this PR be merged?

2022-05-18 13:54 UTC, leahecole approved these changes

2022-05-20 04:48 UTC, dandhlee commented
Closing this in favor of #7921.

2022-05-20 04:48 UTC, closed without merging