Example Airflow DAG that sends an email message through SendGrid
GoogleCloudPlatform/python-docs-samples pull request #7894
Opened 2022-05-13 15:20 UTC by pavel-salnikov

## Description

Example Airflow DAG that sends an email message through SendGrid. 

## Checklist

- [X] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [X] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [X] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2022-05-31 16:29 UTC, leahecole requested changes
1. Please add a unit test - it will likely be very similar to [this test](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/composer/2022_airflow_summit/retries_test.py)
2. Should the schedule interval be daily? I can't remember, but is `catchup` set to True by default? If it is, this is going to run a lot when users first add it to their environments. Do you want to highlight having scheduled notifications? If not, consider having it not be scheduled and have the users trigger it as part of the tutorial

2022-08-30 18:25 UTC, leahecole commented on composer/workflows/email_operator_sendgrid_test.py
> +    import email_operator_sendgrid
```suggestion
    from . import email_operator_sendgrid
```

2022-08-30 18:29 UTC, leahecole approved these changes

2022-08-30 18:38 UTC, dandhlee approved these changes
LGTM for Python.

2022-08-30 18:40 UTC, merged