Update main for Python 3. Use .items() instead of .iteritems()
GoogleCloudPlatform/python-docs-samples pull request #7901
Opened 2022-05-17 18:46 UTC by jlara310

## Update main of datastore/cloud-client/snippets.py for python3

Fixes #7900

Note: It's a good idea to open an issue first for discussion.

## Checklist
- [ x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.6` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ x] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2022-05-17 19:20 UTC, kurtisvg approved these changes

2022-05-18 16:43 UTC, Mariatta commented on datastore/cloud-client/snippets.py
> +    for name, function in list(globals().items()):
I think it was not necessary to convert this into `list`. Was there a reason for doing that?

```suggestion
    for name, function in globals().items():
```

2022-05-18 17:12 UTC, Mariatta requested changes
Thanks for the PR. It's definitely great to make the code works in Python 3.
The rest looks great, but I don't think you need to convert items into `list`.

2022-05-19 18:29 UTC, Mariatta approved these changes
LGTM

2022-05-19 23:01 UTC, merged