rename DAG ID of data_analytics_dag.py
GoogleCloudPlatform/python-docs-samples pull request #8148
Opened 2022-07-01 21:16 UTC by kaiyang-code

## Description

rename DAG ID of data_analytics_dag.py from "summit_dag" to "data_analytics_dag" @leahecole 

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2022-07-01 21:35 UTC, leahecole requested changes
Please remove the empty text file!

2022-07-06 15:06 UTC, leahecole commented
Not sure why python 3.6 is failing but we should actually be able to skip python 3.6 - I'll ping you with info on how to do that

2022-07-06 18:48 UTC, leahecole approved these changes

2022-07-09 17:48 UTC, parthea approved these changes

2022-07-09 17:48 UTC, merged