Update Cloud SQL samples for viewing app on linux GCE VM.
GoogleCloudPlatform/python-docs-samples pull request #8349
Opened 2022-09-22 21:30 UTC by jsimonweb

Update the Cloud SQL sample apps so that when they are run:

`* Running on http://127.0.0.1:8080`

becomes

```
* Running on all addresses (0.0.0.0)
* Running on http://127.0.0.1:8080
```
which enables viewing of the sample app (running on a GCE Linux VM) in a browser on your local computer.

2022-09-23 20:08 UTC, kurtisvg requested changes
Why doesn't 127.0.0.1 work for GCE?

2022-09-23 21:48 UTC, jsimonweb commented
>Why doesn't 127.0.0.1 work for GCE?

The Cloud SQL sample app runs as expected on GCE VMs using 127.0.0.1
The issue is that when the sample app is running on a GCE VM using 127.0.01, attempting to load the sample app in a browser using `http://[GCE-VM-external-ip]:8080` on a local computer, fails with the error: ERR_CONNECTION_REFUSED "This site can’t be reached".

After updating the `app.py` file as is done in this PR, the running sample app loads in a browser on a local computer as expected.

An alternative to this PR would be to instruct developers attempting to use their local computer's browser to view the the app running on a GCE VM, to make this PR's change manually as an additional step in the configuration of the sample app.

2022-09-26 15:39 UTC, kurtisvg commented
@jbsimon Can we use ssh / port forwarding to avoid this? That would be a more secure pattern: https://cloud.google.com/solutions/connecting-securely#port-forwarding-over-ssh

2022-10-06 23:48 UTC, jsimonweb commented
Will update related instructions in product documentation to use port forwarding as suggested.

2022-10-06 23:48 UTC, closed without merging