Migrate code from googleapis/python-datalabeling
GoogleCloudPlatform/python-docs-samples pull request #8456
Opened 2022-11-03 14:47 UTC by ivanmkc

- chore: move samples from python-docs-sample to here (#29)
- feat!: migrate to use microgen (#34)
- samples: updated requierement.txt and enabled list sample test (#48)
- chore: added helpful instruction comment on lable_image sample (#52)
- feat: add common resource helper paths; expose client transport (#49)
- chore: currently datalabeling is limited to due to covid 19 (#61)
- chore: update templates (#63)
- chore: Updating resources and configuration for presubmits and test environments (#72)
- chore: disabling datalabeling tests due to service limited exception (#81)
- chore: migrate to owl bot (#96)
- chore(deps): update dependency pytest to v6.2.4 (#97)
- chore: new owl bot post processor docker image (#103)
- chore(deps): update dependency google-cloud-datalabeling to v1.1.0 (#106)
- chore(deps): update dependency backoff to v1.11.0 (#118)
- chore(deps): update dependency google-cloud-datalabeling to v1.2.0 (#119)
- chore(deps): update dependency backoff to v1.11.1 (#120)
- feat: add Samples section to CONTRIBUTING.rst (#124)
- chore(deps): update dependency google-cloud-datalabeling to v1.2.1 (#126)
- chore(deps): update dependency google-cloud-datalabeling to v1.2.2 (#132)
- chore: fix INSTALL_LIBRARY_FROM_SOURCE in noxfile.py (#134)
- chore: drop mention of Python 2.7 from templates (#136)
- chore(deps): update dependency pytest to v6.2.5 (#141)
- chore: blacken samples noxfile template (#146)
- chore: fail samples nox session if python version is missing (#153)
- chore(python): Add kokoro configs for python 3.10 samples testing (#158)
- chore(deps): update dependency google-cloud-datalabeling to v1.3.0 (#162)
- chore(deps): update dependency google-cloud-datalabeling to v1.4.0 (#168)
- chore(samples): Add check for tests in directory (#181)
- chore(python): Noxfile recognizes that tests can live in a folder (#185)
- chore(deps): update dependency pytest to v7 (#193)
- chore(deps): update dependency pytest to v7.0.1 (#195)
- chore(deps): update dependency google-cloud-datalabeling to v1.5.0 (#196)
- chore: use gapic-generator-python 0.63.2 (#194)
- chore: use gapic-generator-python 0.63.4 (#197)
- chore: update copyright year to 2022 (#198)
- chore: Adding support for pytest-xdist and pytest-parallel (#207)
- chore(deps): update dependency google-cloud-datalabeling to v1.5.1 (#210)
- chore(deps): update dependency pytest to v7.1.0 (#212)
- chore(deps): update dependency pytest to v7.1.1 (#213)
- chore(python): use black==22.3.0 (#218)
- chore: use gapic-generator-python 0.65.1 (#228)
- chore(python): add nox session to sort python imports (#229)
- chore(deps): update dependency pytest to v7.1.2 (#232)
- chore(deps): update dependency backoff to v2 (#233)
- chore(deps): update dependency backoff to v2.0.1 (#235)
- fix: require python 3.7+ (#251)
- chore(deps): update all dependencies (#245)
- chore(deps): update all dependencies (#257)
- chore(deps): update dependency google-cloud-datalabeling to v1.6.1 (#263)
- chore(deps): update dependency pytest to v7.1.3 (#272)
- chore: Bump gapic-generator-python version to 1.3.0 (#273)
- chore: detect samples tests in nested directories (#276)
- chore(deps): update dependency google-cloud-datalabeling to v1.6.2 (#280)
- chore(deps): update dependency backoff to v2.2.1 (#281)
- chore(deps): update dependency google-cloud-datalabeling to v1.6.3 (#284)
- chore(deps): update dependency pytest to v7.2.0 (#285)

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2022-11-03 14:54 UTC, ivanmkc commented
CLA issues caused by previous committers: https://opensource.corp.google.com/github/prinfo?q=%2Fgithub.com%2FGoogleCloudPlatform%2Fpython-docs-samples%2Fpull%2F8456

Should I squash?

2022-11-03 19:55 UTC, dandhlee requested changes

2022-11-03 19:55 UTC, dandhlee commented on datalabeling/snippets/noxfile.py
> +# Copyright 2022 Google LLC
This file is not needed. Please remove.

2022-11-03 19:55 UTC, dandhlee commented on appengine/standard/ndb/cache/README.md
> -## App Engine Datastore NDB Cache Samples
Are these files purposely removed?

2022-11-03 19:55 UTC, dandhlee commented on datalabeling/AUTHORING_GUIDE.md
> +See https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/AUTHORING_GUIDE.md
```suggestion
See https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md
```

2022-11-03 19:55 UTC, dandhlee commented on datalabeling/CONTRIBUTING.md
> +See https://github.com/GoogleCloudPlatform/python-docs-samples/blob/master/CONTRIBUTING.md
```suggestion
See https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/CONTRIBUTING.md
```

2022-11-03 21:38 UTC, nicain commented
@ivanmkc I don't think generated samples are in-scope for the migration. Ill ping the chat line and confirm.

2022-11-04 18:29 UTC, ivanmkc commented on appengine/standard/ndb/cache/README.md
> -## App Engine Datastore NDB Cache Samples
I don't know why or how they where removed..

2022-11-04 18:32 UTC, ivanmkc commented on appengine/standard/ndb/cache/README.md
> -## App Engine Datastore NDB Cache Samples
Fixed.

2022-11-07 23:21 UTC, dandhlee requested changes
Could you add a CODEOWNERS and blunderbuss for these files? Otherwise LGTM.

2022-11-08 16:00 UTC, ivanmkc commented
@dandhlee can you re-review?

2022-11-08 18:42 UTC, dandhlee commented on .github/blunderbuss.yml
> +  - python-sample-reviewers
```suggestion
  - GoogleCloudPlatform/python-samples-reviewers
```

2022-11-08 20:19 UTC, ivanmkc commented
@dandhlee needs an override.

2022-11-09 17:15 UTC, dandhlee approved these changes
LGTM. Overriding CLA and admin merging.

2022-11-09 17:36 UTC, merged