chore(functions/tips-lazy-globals): Update sample signature using functions framework
GoogleCloudPlatform/python-docs-samples pull request #8838
Opened 2022-12-28 00:51 UTC by tyampad

Update [Lazy globals sample](http://cloud/functions/docs/samples/functions-tips-lazy-globals) to use functions framework.

Tested by:

Running local tests
Deploying and invoking using curl

2023-01-03 19:33 UTC, ace-n commented
@tyampad thanks for the PR! Can you fix the lint error?

> ./main.py:31:1: E402 module level import not at top of file
import functions_framework
^
nox > Command flake8 --show-source --builtin=gettext --max-complexity=20 --import-order-style=google '--exclude=.nox,.cache,env,lib,generated_pb2,*_pb2.py,*_pb2_grpc.py' --ignore=ANN101,E121,E123,E126,E203,E226,E24,E266,E501,E704,W503,W504,I202 --max-line-length=88 --application-import-names main_test,noxfile,.nox,main . failed with exit code 1
nox > Session lint failed.
PWD: /workspace/functions/tips-lazy-globals

2023-01-03 19:35 UTC, ace-n requested changes

2023-01-03 19:35 UTC, ace-n commented on functions/tips-lazy-globals/main.py
> +import functions_framework
To fix the lint error:
1) Move this import statement to the top of the file (e.g. line 15)
2) Break the sample up into multiple region tags, a la:
```
// [START tag]
<imports go here>
// [END tag]

...

// [START tag]
<code goes here>
// [END tag]
```

2023-01-04 20:03 UTC, ace-n requested changes

2023-01-04 20:03 UTC, ace-n commented on functions/tips-lazy-globals/main.py
> +import functions_framework
Nit: add newline after import statement _within the region-tagged block_
```suggestion
import functions_framework

```

2023-01-04 20:03 UTC, ace-n commented on functions/tips-lazy-globals/main.py
>  from functools import reduce  # noqa I100
Can we delete this import?

2023-01-04 22:57 UTC, ace-n approved these changes

2023-01-05 00:02 UTC, nicain approved these changes

2023-01-05 00:02 UTC, merged