Adding KubernetesPodOperator example for Composer 2
GoogleCloudPlatform/python-docs-samples pull request #8842
Opened 2022-12-28 14:33 UTC by rafalbiegacz

## Description

Adding KubernetesPodOperator example for Composer 2.
It updates information about the namespace, properly configures requests and limits for Autopilot clusters.

## Checklist
- [x] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [x] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [x] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [x] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [x] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [x] Please **merge** this PR for me once it is approved.
- [x] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2023-01-03 16:23 UTC, leahecole requested changes
- Please rename the files to kubernetes_pod_operator_c2.py and kubernetes_pod_operator_c2_test.py - that way they'll show up grouped with the other KPO file. This should also fix your test failure
- Please remove the pylint disable and run "black" on your code. This can be done via the nox session and you can also run lint locally with a nox session (more info on that in the [Authoring guide](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md) - ping me if you need help) - I recommend doing this AFTER adding in my suggestions just in case I accidentally introduce a whitespace error 😅 
- Please accept the suggestions that add in region tags - @pavel-salnikov will need these so that we can properly embed the code in the docs

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +# distributed under the License is distributed on an {{ quot_code }}AS IS{{ quot_code }} BASIS,
```suggestion
# distributed under the License is distributed on an "AS IS" BASIS,
```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +# Licensed under the Apache License, Version 2.0 (the {{ quot_code }}License{{ quot_code }});
```suggestion
# Licensed under the Apache License, Version 2.0 (the "License");
```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +# pylint: disable=bad-indentation
```suggestion
```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +
```suggestion
# [START composer_2_kubernetespodoperator_secretobject]
```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +# If you are running Airflow in more than one time zone
```suggestion
# [END composer_2_kubernetespodoperator_secretobject]
# If you are running Airflow in more than one time zone
```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +
```suggestion
# [START composer_2_kubernetespodoperator]
```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +    )
```suggestion
    )
    # [END composer_2_kubernetespodoperator_fullconfig]
    # [END composer_2_kubernetespodoperator]

```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +    kubernetes_min_pod = KubernetesPodOperator(
```suggestion
    # [START composer_2_kubernetespodoperator_minconfig]
    kubernetes_min_pod = KubernetesPodOperator(
```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +    kubernetes_template_ex = KubernetesPodOperator(
```suggestion
    # [END composer_2_kubernetespodoperator_minconfig]
    # [START composer_2_kubernetespodoperator_templateconfig]
    kubernetes_template_ex = KubernetesPodOperator(
```

2023-01-03 16:23 UTC, leahecole commented on composer/workflows/c2-kubernetes_pod_operator.py
> +    kubernetes_full_pod = KubernetesPodOperator(
```suggestion
    # [END composer_2_kubernetespodoperator_secretconfig]
    # [START composer_2_kubernetespodoperator_fullconfig]
    kubernetes_full_pod = KubernetesPodOperator(
```

2023-01-05 10:09 UTC, pavel-salnikov approved these changes

2023-01-05 16:04 UTC, leahecole approved these changes

2023-01-05 16:18 UTC, merged