add function and dag
GoogleCloudPlatform/python-docs-samples pull request #8860
Opened 2023-01-04 17:00 UTC by dmitriy-drogovoz

2023-01-04 18:10 UTC, leahecole commented
Note for other reviewers: This PR is a submission from TVCs that I and the Cloud Composer team have been working with - we've done an extensive review of the Composer-y aspects of the code in their fork and are now looking for final style review - I'm about to add suggestions for region tags @pavel-salnikov

2023-01-04 18:54 UTC, leahecole requested changes
1. Please move the function and its test to the `composer/functions` directory - they can be renamed `pubsub_publisher.py` and `pubsub_publisher_test.py` instead of `main.py` and `main_test.py`
2. Add `google-cloud-pubsub==2.13.11` to `composer/functions/requirements.txt` - I think that `google-cloud` isn't needed (I don't see it imported anywhere, but if I'm wrong, let me know)
3. Resolve test failures in the function test - there are NameErrors about `pubsub_function` not being defined. To replicate how the CICD runs the tests locally, copy [`noxfile-template.py`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/noxfile-template.py) to `composer/functions` (once you've moved the code there) and run `nox -s py-3.8`. See the [Authoring guide](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md) for more info
4. Resolve lint failures - to replicate the lint session locally, once you have that noxfile from 3 in your directory (you can do the same for the `composer/workflows` directory) you can run `nox -s lint` 

Once this is done, I will add commit suggestions in the code that add "region tags" - comments that will enable @pavel-salnikov to embed the code in the docs

2023-01-09 17:40 UTC, leahecole commented
I have triggered the lint job re-run in fusion and it's queued

2023-01-09 20:35 UTC, leahecole requested changes
1. Please remove the zip file - users can download the dag and function separately without them needing to be zipped together
2. Please accept the suggestions which will add the region tags for @pavel-salnikov

2023-01-09 20:35 UTC, leahecole commented on composer/functions/pubsub_publisher.py
> +
```suggestion

# [START composer_pubsub_publisher_function]
```

2023-01-09 20:35 UTC, leahecole commented on composer/functions/pubsub_publisher.py
> +    return f"Message {data} with message_length {message_length} published to {topic_path}."
```suggestion
    return f"Message {data} with message_length {message_length} published to {topic_path}."
# [END composer_pubsub_publisher_function]
```

2023-01-09 20:35 UTC, leahecole commented on composer/workflows/pubsub_trigger_response_dag.py
> +
```suggestion

# [START composer_pubsub_trigger_dag]
```

2023-01-09 20:35 UTC, leahecole commented on composer/workflows/pubsub_trigger_response_dag.py
> +    (some_heavy_task)
```suggestion
    (some_heavy_task)
# [END composer_pubsub_trigger_dag]
```

2023-01-12 19:07 UTC, leahecole approved these changes
@pavel-salnikov PTAL 😄

2023-01-16 08:32 UTC, pavel-salnikov approved these changes

2023-01-17 16:23 UTC, leahecole commented
I manually retriggered lint and 3.8

2023-01-17 16:46 UTC, merged