test: reduce testing to 2 python versions per sample
GoogleCloudPlatform/python-docs-samples pull request #8875
Opened 2023-01-06 16:30 UTC by parthea

Please review https://github.com/GoogleCloudPlatform/python-docs-samples/pull/8872 first

Once https://github.com/GoogleCloudPlatform/python-docs-samples/pull/8872 is merged, the versions of python tested will be 2.7, 3.7, 3.8, 3.9, 3.10 and 3.11

To save on resources, let's restrict testing to the end points. So, 3.7 and 3.11 (plus 2.7 when needed).

2023-01-09 20:36 UTC, leahecole commented
@parthea I know that Composer is an edge case that for now only is in Python 3.8. How should we handle such cases? otherwise I think this is a great idea

2023-01-09 20:37 UTC, leahecole commented
removed earlier comment, realized we were editing the noxfile configs per product not the base test image. sorry!

2023-01-10 20:11 UTC, ace-n commented
FYI: App Engine [does not fully support 3.11 yet](https://cloud.google.com/appengine/docs/flexible/python/runtime#:~:text=App%20Engine%20standard%20environment%3A%20Python,3.9%2C%20and%203.10%20are%20supported.).

2023-01-10 21:53 UTC, leahecole commented
Composer LGTM
data-science-onramp - I am seeing the protocol buffers descriptors error (but don't with Python 3.10 or below) - I am wondering if it's really just that python-aiplatform isn't ready yet?

2023-01-10 21:56 UTC, leahecole commented
I'm going to merge with main to kick off another build but I'm thinking that...

3.7
- retail failure looks like it might be resolved by #8968 

3.11
- dataproc should be fixed now that I gave the default service account permissions
- talent/jobs should be resolved from enabling the api and approving the log thing
- healthcare should be resolved since we enabled the api
- secretmanager should be resolved since we enabled the API

2023-01-10 22:01 UTC, dandhlee commented
I believe some products only serve 3.8 or 3.9 (Run and Data* products).

Fundamentally, I'd strongly push back against making this change. If users run into problems before we do, simply because we reduced the number of versions being tested, that'd be a really bad experience for everyone.

If we want to save resources, can we run the nightly / continuous less frequently instead?

2023-01-11 14:43 UTC, kweinmeister commented
@dandhlee I believe this change does not affect samples that have a dependency on a specific version (e.g. 3.8 or 3.9). It should only address projects with open-ended 3.x support. If there are spots where the PR is not meeting this criteria, we should definitely update it.

This PR is aligned with a risk-based testing strategy that is followed in other languages (e.g. Java 8, 11, 17 and not 8..17). If the endpoints are both passing, the risk of a deterministic language-specific issue in 3.8..3.10 is very low and acceptable for sample code given tradeoffs IMO. We can incrementally add versions back to the matrix if such issues arise -- e.g. a midpoint version (3.9) next. Also, in addition to this change, as you suggested we can review the frequency of periodic builds.

FYI @nicain

2023-01-11 16:04 UTC, leahecole commented
> FYI: App Engine [does not fully support 3.11 yet](https://cloud.google.com/appengine/docs/flexible/python/runtime#:~:text=App%20Engine%20standard%20environment%3A%20Python,3.9%2C%20and%203.10%20are%20supported.).

@ace-n the doc you linked is for app engine standard, but iiuc these tests are for app engine flexible - does flexible also not support 3.11?

2023-01-11 23:50 UTC, ace-n commented
@leahecole here's my understanding:

### GAE Flex
Flexible [supports](https://cloud.google.com/appengine/docs/flexible/python/runtime) Python 3.4 - 3.7.

### GAE Standard
The App Engine standard template (`appengine/standard/noxfile-template.py`)'s `TEST_CONFIG["ignored_versions"]` **does not match** the `IGNORED_VERSIONS` variable lower in the file, and I'm not sure which one takes priority.

### GAE `standard_python3`
For `appengine/standard_python3` - this PR would test `3.7` and `3.11`. I assume we should change `3.11` to `3.10`? (cc @engelke as FYI)

2023-01-12 20:59 UTC, leahecole commented on appengine/standard_python3/bundled-services/blobstore/django/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 20:59 UTC, leahecole commented on appengine/standard_python3/bundled-services/blobstore/flask/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:00 UTC, leahecole commented on appengine/standard_python3/bundled-services/blobstore/wsgi/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:00 UTC, leahecole commented on appengine/standard_python3/bundled-services/deferred/django/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:00 UTC, leahecole commented on appengine/standard_python3/bundled-services/deferred/flask/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:00 UTC, leahecole commented on appengine/standard_python3/bundled-services/deferred/wsgi/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:00 UTC, leahecole commented on appengine/standard_python3/bundled-services/mail/django/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:01 UTC, leahecole commented on appengine/standard_python3/bundled-services/deferred/django/noxfile_config.py
> +    # Test min and max supported versions which are python 3.7 and 3.11
```suggestion
    # Test min and max supported versions which are python 3.7 and 3.10
```

2023-01-12 21:01 UTC, leahecole commented on appengine/standard_python3/bundled-services/deferred/flask/noxfile_config.py
> +    # Test min and max supported versions which are python 3.7 and 3.11
```suggestion
    # Test min and max supported versions which are python 3.7 and 3.10
```

2023-01-12 21:01 UTC, leahecole commented on appengine/standard_python3/bundled-services/deferred/wsgi/noxfile_config.py
> +    # Test min and max supported versions which are python 3.7 and 3.11
```suggestion
    # Test min and max supported versions which are python 3.7 and 3.10
```

2023-01-12 21:01 UTC, leahecole commented on appengine/standard_python3/bundled-services/mail/django/noxfile_config.py
> +    # Test min and max supported versions which are python 3.7 and 3.11
```suggestion
    # Test min and max supported versions which are python 3.7 and 3.10
```

2023-01-12 21:01 UTC, leahecole commented on appengine/standard_python3/bundled-services/mail/flask/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    # Test min and max supported versions which are python 3.7 and 3.10
    # Ignoring python 2.7 which is no longer supported.
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:01 UTC, leahecole commented on appengine/standard_python3/bundled-services/mail/wsgi/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    # Test min and max supported versions which are python 3.7 and 3.10
    # Ignoring python 2.7 which is no longer supported.
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:02 UTC, leahecole commented on appengine/standard_python3/django/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    # Test min and max supported versions which are python 3.7 and 3.10
    # Ignoring python 2.7 which is no longer supported.
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:02 UTC, leahecole commented on asset/snippets/noxfile_config.py
> +    "ignored_versions": ["2.7", "3.8", "3.9", "3.10"],
```suggestion
    # Test min and max supported versions which are python 3.7 and 3.10
    # Ignoring python 2.7 which is no longer supported.
    "ignored_versions": ["2.7", "3.8", "3.9", "3.11"],
```

2023-01-12 21:07 UTC, leahecole requested changes
requesting changes to appengine per @ace-n 's comment

2023-04-19 21:41 UTC, engelke commented
A lot has changed since this PR was proposed, and there are a lot of items for discussion. Could we close this for now and revisit the whole thing following some planned fixes?

2023-04-19 23:58 UTC, closed without merging