migrate code from googleapis/python-speech
GoogleCloudPlatform/python-docs-samples pull request #8982
Opened 2023-01-13 19:59 UTC by telpirion

- Add generated code samples. (#9153)
- Update samples manifest (via synth). (#9211)
- codegen(speech): reorder samples (#9313)
- chore(speech): bump copyright year to 2020, tweak docstring formatting (via synth) (#10238)
- speech: remove erroneous comment (#17)
- Add quickstart sample for the Cloud Speech API. [(#658)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/658)
- Update readmes
- Auto-update dependencies. [(#715)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/715)
- Add cloud-client samples for speech [(#775)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/775)
- Adds usage examples to api-client samples and fixes copy/paste error in cloud-client/transcribe. [(#782)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/782)
- Add speech GCS samples [(#784)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/784)
- Updates client version for compatibility with language [(#842)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/842)
- Adds streaming snippet for howto [(#881)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/881)
- Remove resource [(#890)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/890)
- Speech v1 [(#889)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/889)
- Changes docs for async playback to point to LINEAR16 example [(#897)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/897)
- Speech version bump [(#899)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/899)
- Update transcribe_async.py to have long GCS flac example [(#904)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/904)
- Re-generate all readmes
- Fix typo [(#926)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/926)
- Fix README rst links [(#962)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/962)
- Auto-update dependencies. [(#1004)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1004)
- Speech sample using microphone [(#1013)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1013)
- Speech gapic client library [(#1012)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1012)
- use region tags [(#1022)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1022)
- Auto-update dependencies. [(#1039)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1039)
- add word time offsets to async sample [(#1042)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1042)
- Add word time offset samples [(#1050)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1050)
- Remove old parameter enable_word_time_offsets [(#1054)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1054)
- Auto-update dependencies. [(#1055)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1055)
- Auto-update dependencies. [(#1093)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1093)
- Print all results, not all alternatives [(#1098)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1098)
- quickstart: print out all results. [(#1108)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1108)
- Update all generated readme auth instructions [(#1121)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1121)
- Added Link to Python Setup Guide [(#1158)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1158)
- Auto-update dependencies. [(#1186)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1186)
- Added "Open in Cloud Shell" buttons to README files [(#1254)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1254)
- Speech: clarify comments. [(#1278)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1278)
- Auto-update dependencies. [(#1320)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1320)
- Auto-update dependencies. [(#1355)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1355)
- Auto-update dependencies. [(#1359)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1359)
- Speech model selection [(#1361)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1361)
- Auto-update dependencies. [(#1377)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1377)
- Speech API: enhanced model and recognition metadata [(#1436)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1436)
- Regenerate the README files and fix the Open in Cloud Shell link for some samples [(#1441)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1441)
- add Speech API auto punctuation sample [(#1446)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1446)
- use unicode [(#1453)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1453)
- Update READMEs to fix numbering and add git clone [(#1464)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1464)
- Diarization [(#1556)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1556)
- Multi Channel [(#1561)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1561)
-  Multi Langauge [(#1564)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1564)
- Added the sample for Word Level Confidence [(#1567)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1567)
- Diarization Output Modified [(#1586)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1586)
- Speech region tag update [(#1644)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1644)
- Update enhanced models and auto punctuation to GA [(#1702)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1702)
- Test form of result only, not contents [(#1866)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1866)
- speech: updated README for model selection sample [(#1892)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1892)
- Speech continuous [(#1940)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1940)
- Add missing import for code sample [(#1898)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1898)
- Auto-update dependencies. [(#1980)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/1980)
- add speech api multichannel samples [(#2003)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2003)
- Move mic samples out of cloud-client so that cloud-client samples can be run in cloud shell [(#2062)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2062)
- Move mic samples out of cloud-client so that cloud-client samples can be run in cloud shell [(#2062)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2062)
- Place import inside the function [(#2209)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2209)
- adding infinite streaming sample to samples folder, unlike indefinite… [(#2161)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2161)
- Increase timeout to 5 mins [(#2206)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2206)
- Python 2 compatibility for print statements [(#2226)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2226)
- Enhanced models are available to all projects [(#2207)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2207)
- Adds updates for samples profiler ... vision [(#2439)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2439)
- Adds updates for samples profiler ... vision [(#2439)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2439)
- Update transcribe_streaming.py [(#2597)](https://github.com/GoogleCloudPlatform/python-docs-samples/issues/2597)
- Au [...]

2023-01-13 22:00 UTC, kweinmeister commented
2.7 build error:
```
#
# speech/snippets
#

------------------------------------------------------------
- testing /workspace/speech/snippets
------------------------------------------------------------
nox > Error while collecting sessions.
nox > Sessions not found: py-2.7
No user noxfile_config found: detail: No module named 'noxfile_config'
PWD: /workspace/speech/snippets

 Testing failed: Nox returned a non-zero exit code. 
```

2023-01-24 00:23 UTC, nicain approved these changes

2023-01-27 14:16 UTC, kweinmeister commented
@telpirion Should we include the CODEOWNERS and blunderbuss.yml updates, too?

@nicain @m-strzelczyk @dandhlee These changes are blocked by an invalid license header, "Google Inc" rather than "Google, Inc." Given that these are existing files, should we update the configuration to allow "Google Inc" or do you have another suggestion to move forward?

2023-02-03 12:03 UTC, dandhlee commented
We should fix the license headers, if they're deemed invalid (slight tweak to fix them is fine).

2023-02-03 12:16 UTC, dandhlee requested changes
Please add `CODEOWNERS` and `blunderbuss.yml` for `api: speech`.

2023-02-03 12:16 UTC, dandhlee commented on speech/microphone/noxfile_config.py
> +# Copyright 2019 Google LLC
Remove this file.

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/noxfile_config.py
> +# Copyright 2019 Google LLC
Ditto.

2023-02-03 12:16 UTC, dandhlee commented on speech/microphone/transcribe_streaming_mic.py
> +# Copyright 2017 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2017 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/microphone/transcribe_streaming_mic_test.py
> +# Copyright 2017, Google, Inc.
```suggestion
# Copyright 2017 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/adaptation_v2_custom_class_reference.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/adaptation_v2_custom_class_reference_test.py
> +# Copyright 2022, Google, Inc.
```suggestion
# Copyright 2017 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/adaptation_v2_inline_custom_class.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/adaptation_v2_inline_custom_class_test.py
> +# Copyright 2022, Google, Inc.
```suggestion
# Copyright 2022 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/adaptation_v2_inline_phrase_set.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/adaptation_v2_inline_phrase_set_test.py
> +# Copyright 2022, Google, Inc.
```suggestion
# Copyright 2022 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/adaptation_v2_phrase_set_reference.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/adaptation_v2_phrase_set_reference_test.py
> +# Copyright 2022, Google, Inc.
```suggestion
# Copyright 2022 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/beta_snippets.py
> +# Copyright 2018 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2018 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/beta_snippets_test.py
> +# Copyright 2018, Google, Inc.
```suggestion
# Copyright 2018 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/create_recognizer.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/create_recognizer_test.py
> +# Copyright 2022, Google, Inc.
```suggestion
# Copyright 2022 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/quickstart.py
> +# Copyright 2016 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2016 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/quickstart_test.py
> +# Copyright 2016 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2016 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/quickstart_v2.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/quickstart_v2_test.py
> +# Copyright 2022, Google, Inc.
```suggestion
# Copyright 2022 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe.py
> +# Copyright 2017 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2017 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_async_file.py
> +# Copyright 2021 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2021 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_async_file_test.py
> +# Copyright 2021, Google, Inc.
```suggestion
# Copyright 2021 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_async_gcs.py
> +# Copyright 2021 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2021 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_async_gcs_test.py
> +# Copyright 2021, Google, Inc.
```suggestion
# Copyright 2021 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_auto_punctuation_test.py
> +# Copyright 2018, Google LLC
```suggestion
# Copyright 2018 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_context_classes_test.py
> +# Copyright 2020, Google LLC
```suggestion
# Copyright 2020 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_enhanced_model_test.py
> +# Copyright 2018, Google LLC
```suggestion
# Copyright 2018 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_file_v2.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_file_v2_test.py
> +# Copyright 2022, Google, Inc.
```suggestion
# Copyright 2022 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_gcs_v2.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_gcs_v2_test.py
> +# Copyright 2022, Google, Inc.
```suggestion
# Copyright 2022 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_model_selection.py
> +# Copyright 2017 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2017 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_model_selection_test.py
> +# Copyright 2016, Google, Inc.
```suggestion
# Copyright 2016 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_multichannel.py
> +# Copyright 2019 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2019 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_onprem/transcribe_onprem.py
> +# Copyright 2020, Google LLC
```suggestion
# Copyright 2020 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_streaming.py
> +# Copyright 2017 Google Inc. All Rights Reserved.
```suggestion
# Copyright 2017 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_streaming_test.py
> +# Copyright 2017, Google, Inc.
```suggestion
# Copyright 2017 Google LLC

```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_streaming_v2.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-03 12:16 UTC, dandhlee commented on speech/snippets/transcribe_streaming_voice_activity_events.py
> +# Copyright 2022 Google Inc.
```suggestion
# Copyright 2022 Google LLC
```

2023-02-08 02:10 UTC, telpirion commented on speech/snippets/noxfile_config.py
> +# Copyright 2019 Google LLC
Done.

2023-02-08 02:10 UTC, telpirion commented on speech/snippets/transcribe_streaming_voice_activity_timeouts.py
> +# Copyright 2022 Google Inc.
Done.

2023-02-08 02:10 UTC, telpirion commented on speech/snippets/transcribe_streaming_voice_activity_timeouts_test.py
> +# Copyright 2022, Google, Inc.
Done.

2023-02-08 02:11 UTC, telpirion commented on speech/snippets/transcribe_word_time_offsets_test.py
> +# Copyright 2016, Google, Inc.
Done.

2023-02-08 19:15 UTC, telpirion commented
Thank you, @dandhlee !

2023-02-09 00:18 UTC, dandhlee commented
Seems like tests are passing now! I don't anticipate 3.9 failing for a different reason. Overriding CLA and admin merging.

2023-02-09 00:19 UTC, merged