migrate code from googleapis/python-dialogflow-cx
GoogleCloudPlatform/python-docs-samples pull request #9077
Opened 2023-02-01 20:34 UTC by soheilazangeneh

- docs(samples): add initial sample codes (#13)
- fix: corrects the repo/homepage link (#15)
- chore(deps): update dependency google-cloud-dialogflow-cx to v0.1.1 (#16)
- chore(deps): update dependency google-cloud-dialogflow-cx to v0.2.0 (#26)
- Sample code update for regionalization (#29)
- chore(deps): update dependency google-cloud-dialogflow-cx to v0.4.0 (#49)
- chore(deps): update dependency google-cloud-dialogflow-cx to v0.4.1 (#79)
- chore(deps): update dependency pytest to v6.2.4 (#82)
- chore(deps): update dependency google-cloud-dialogflow-cx to v0.5.0 (#97)
- chore(deps): update dependency google-cloud-dialogflow-cx to v0.6.0 (#101)
- chore(deps): update dependency google-cloud-dialogflow-cx to v0.7.1 (#109)
- chore(deps): update dependency google-cloud-dialogflow-cx to v0.8.0 (#121)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1 (#123)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.1.0 (#132)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.1.1 (#136)
- docs(samples): add agent creation code snippet (#146)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.2.0 (#140)
- docs(samples): add update intent sample (#142)
- chore: generate python samples templates in owlbot.py (#149)
- docs(samples): add region tags (#150)
- docs(samples): add region tags (#151)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.3.0 (#160)
- chore(deps): update dependency pytest to v6.2.5 (#158)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.3.1 (#163)
- docs(samples): added page management samples (#152)
- chore: blacken samples noxfile template (#170)
- docs(samples): added filter sample (#171)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.3.2 (#175)
- chore: fail samples nox session if python version is missing (#180)
- chore(python): Add kokoro configs for python 3.10 samples testing (#188)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.4.0 (#185)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.5.0 (#190)
- docs(samples): add voice selection (#184)
- docs(samples): added webhook sample (#169)
- docs(samples): adds list training phrases sample (#196)
- chore(deps): update dependency flask to v2.0.2 (#194)
- docs(samples): added comment to webhook sample (#211)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.6.0 (#205)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.7.0 (#213)
- docs(samples): Added LRO code snippet (#220)
- chore(samples): Add check for tests in directory (#227)
- chore(python): Noxfile recognizes that tests can live in a folder (#234)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.8.0 (#233)
- chore(deps): update dependency pytest to v7 (#246)
- chore: use gapic-generator-python 0.63.1 (#245)
- chore(deps): update all dependencies (#251)
- chore(deps): update all dependencies (#256)
- chore: Adding support for pytest-xdist and pytest-parallel (#264)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.9.1 (#267)
- chore(deps): update all dependencies (#271)
- chore(deps): update dependency pytest to v7.1.1 (#272)
- chore(python): use black==22.3.0 (#282)
- chore(deps): update dependency flask to v2.1.0 (#280)
- chore(deps): update dependency flask to v2.1.1 (#284)
- chore(python): add nox session to sort python imports (#295)
- chore(deps): update dependency pytest to v7.1.2 (#299)
- chore(deps): update dependency flask to v2.1.2 (#301)
- docs(samples): Adds snippet for validating a form parameter. (#302)
- docs(samples): Configure session parameters snippet (#303)
- docs(samples): Configure session parameters trigger transition (#304)
- docs(samples): Adds snippet for configuring optional or required form parameters (#305)
- docs(samples): Adds snippet for configuring a webhook to enable an agent response. (#306)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.11.0 (#308)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.12.0 (#315)
- chore: Update dialogflow_cx_webhook snippet to match NodeJS (#409)
- chore: Dialogflow cx v3 webhook validate form parameter (#410)
- chore: update dialogflow_cx_v3_webhook_configure_session_parameters snippet (#411)
- chore: Remove refactored webhook snippets (#412)
- docs: add streaming detect intent with partial response sample (#414)
- docs: add detect intent with sentiment analysis snippet (#416)
- docs: add detect intent with intent input snippet (#417)
- docs: add detect intent with text-to-speech synthesized output snippet (#419)
- docs: Dialogflow cx v3 detect intent event input snippet (#421)
- fix: Update detect_intent_synthesize_tts_response.py (#423)
- docs: Add dialogflow cx detect intent with disabled webhook snippet (#422)
- chore(python): drop python 3.6 (#420)
- docs: Update region_tag: dialogflow_detect_intent_text --> dialogflow_cx_detect_intent_text (#424)
- chore(deps): update all dependencies (#429)
- chore(deps): update all dependencies (#430)
- chore(deps): update all dependencies (#431)
- chore(deps): update all dependencies (#432)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.13.1 (#438)
- docs(samples): Add prebuilt telecom agent webhook code in python (#434)
- chore(deps): update dependency pytest to v7.1.3 (#450)
- chore: detect samples tests in nested directories (#456)
- feat: Adding snippet to extract SessionInfo (#457)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.13.4 (#464)
- chore(deps): update dependency pytest to v7.2.0 (#467)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.13.5 (#468)
- chore(python): drop flake8-import-order in samples noxfile (#473)
- fix(deps): Require google-api-core >=1.34.0, >=2.11.0 (#469)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.14.0 (#476)
- docs(samples): Update previous month logic to avoid zero-index bug in webhook_prebuilt_telecom sample (#479)
- chore(python): add support for python 3.11 (#477)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.14.1 (#481)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.15.0 (#484)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.16.0 (#487)
- chore(deps): update dependency pytest to v7.2.1 (#490)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.17.0 (#491)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.17.1 (#494)
- chore(deps): update dependency google-cloud-dialogflow-cx to v1.18.0 (#499)

## Description

Fixes #<ISSUE-NUMBER>

Note: Before submitting a pull request, please open an issue for discussion if you are not associated with Google.

## Checklist
- [ ] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [ ] README is updated to include [all relevant information](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#readme-file)
- [ ] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [ ] These samples need a new **API enabled** in testing projects to pass (let us know which ones)
- [ ] These samples need a new/updated **env vars** in testing projects set to pass (let us know which ones)
- [ ] Please **merge** this PR for me once it is approved.
- [ ] This sample adds a new sample directory, and I updated the [CODEOWNERS file](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/CODEOWNERS) with the codeowners for this sample

2023-02-03 11:41 UTC, dandhlee requested changes
Could you also add an entry for `api: dialogflow` on the [`blunderubss.yml`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml)?

2023-02-03 11:41 UTC, dandhlee commented on dialogflow-cx/noxfile.py
> +# Copyright 2023 Google LLC
Remove this file.

2023-02-07 23:24 UTC, holtskinner approved these changes

2023-02-08 02:35 UTC, dandhlee commented on .github/CODEOWNERS
> +/dialogflow-cx/**/*                    @GoogleCloudPlatform/python-samples-reviewers
```suggestion
/dialogflow-cx/**/*                    @GoogleCloudPlatform/dee-data-ai @GoogleCloudPlatform/python-samples-reviewers
```

2023-02-08 02:35 UTC, dandhlee approved these changes

2023-02-08 03:12 UTC, merged