fix: change dialogflow intent display name
GoogleCloudPlatform/python-docs-samples pull request #9174
Opened 2023-02-26 19:49 UTC by kweinmeister

Main change is to make the `display_name` unique (line 36). This test was failing because there is an existing intent with "fake_intent" in the test project. Now it adds a UUID to the end of the display name.

Typing was also added to the test file along with this fix.

Fixes #9154

2023-02-26 22:57 UTC, yil532 approved these changes
LGTM

2023-02-27 12:02 UTC, m-strzelczyk requested changes
I see you duplicated a fix that I tried to do (#9158), but yours is better :) Thanks for fixing adding all the type annotations.

Left one comment to fix.

2023-02-27 12:02 UTC, m-strzelczyk commented on dialogflow/update_intent_test.py
> +    actual_response: Intent = update_intent(PROJECT_ID, pytest.INTENT_ID, fake_intent)
You are changing the name of the intent here from `fake_intent_{INTENT_SUFFIX}` to `fake_intent_{INTENT_SUFFIX}`. IMO you should leave `fake_intent_{uuid.uuid4()}` as the new name.

2023-02-27 14:19 UTC, m-strzelczyk commented
The 3.11 failed because the API was not enabled. I think I have enabled the Dialogflow api for the 3.11 project. Waiting for new run of the tests. Should be fine, unless theres' something more that needs to be done in the project for Dialogflow to work.

2023-03-15 16:03 UTC, m-strzelczyk commented
It took me some time, but I managed to configure the 3.11 project and now the tests should pass. I sent a CL to update our docs about setting up the new project.

2023-03-15 16:04 UTC, merged