Chore: skip failling tests to get periodic tests back to green state
GoogleCloudPlatform/python-docs-samples pull request #9192
Opened 2023-03-01 13:36 UTC by rsamborski

## Description

Skip failing tests to get periodic CI/CD tests back to green state

## Checklist
- [X] I have followed [Sample Guidelines from AUTHORING_GUIDE.MD](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md)
- [X] **Tests** pass:   `nox -s py-3.9` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [X] **Lint** pass:   `nox -s lint` (see [Test Environment Setup](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/AUTHORING_GUIDE.md#test-environment-setup))
- [X] Please **merge** this PR for me once it is approved.

2023-03-01 15:05 UTC, leahecole requested changes
Please add a link to the issues to fix these skipped tests in the PR description 🙂 I saw they're inline too, but having it in the description also helps if folks look at Git blame

2023-03-01 19:56 UTC, leahecole approved these changes

2023-03-01 19:57 UTC, leahecole commented
removing automerge until we get a second reviewer then we can re-add!

2023-03-02 15:05 UTC, arbrown approved these changes

2023-03-02 16:36 UTC, merged