chore: add Readme for DLP
GoogleCloudPlatform/python-docs-samples pull request #9198
Opened 2023-03-01 20:27 UTC by Sita04

Add README for DLP. Testing the CODEOWNERS and notifications workflow for the DLP team.

2023-03-01 20:46 UTC, realjordanna commented on dlp/snippets/README.md
> +`Google Data Loss Prevention` provides programmatic access to a powerful
let me check on this real quick ... this summary has changed dramatically in production to

Cloud DLP enables enterprises to automatically discover, classify, and protect their most sensitive data elements.

Running it by one other person. I'll get right back to you.

2023-03-01 21:13 UTC, realjordanna requested changes

2023-03-01 21:13 UTC, realjordanna commented on dlp/snippets/README.md
> +`Google Data Loss Prevention` provides programmatic access to a powerful
Got it. 

branding must either be:

Long name: Cloud Data Loss Prevention
Short name: Cloud DLP

So change this to 

Cloud Data Loss Prevention enables enterprises to automatically discover, classify, and protect their most sensitive data elements.

2023-03-01 21:25 UTC, Sita04 commented
Thanks Jordanna for the updated description. Changing it now.

2023-03-02 08:56 UTC, rsamborski approved these changes

2023-03-02 08:56 UTC, merged