feat(datastore): adds query filter OR
GoogleCloudPlatform/python-docs-samples pull request #9315
Opened 2023-03-20 23:04 UTC by telpirion

This sample adds the following region tags:

+ datastore_query_filter_or

2023-03-22 13:37 UTC, kweinmeister approved these changes

2023-03-22 20:24 UTC, nicain commented on datastore/cloud-client/query_filter_or.py
> +Builds a union (OR) query filter.
Move outside region tags, single whitespace after license header and two whitespace before START tag

2023-03-22 20:24 UTC, nicain commented on datastore/cloud-client/query_filter_or.py
> +
nit: remove whitespace

2023-03-22 20:26 UTC, nicain requested changes

2023-03-24 18:15 UTC, nicain commented on datastore/cloud-client/query_filter_or_test.py
> +    assert "Feed cats" in out
nit: end in newline

2023-03-24 18:20 UTC, telpirion commented on datastore/cloud-client/query_filter_or.py
> +
Done.

2023-03-24 18:20 UTC, telpirion commented on datastore/cloud-client/query_filter_or.py
> +
Done.

2023-03-24 19:19 UTC, nicain approved these changes

2023-03-24 19:20 UTC, merged