Update CODEOWNERS to include functions-framework-google
GoogleCloudPlatform/python-docs-samples pull request #9329
Opened 2023-03-22 18:26 UTC by kenneth-rosario

2023-03-25 17:21 UTC, m-strzelczyk requested changes

2023-03-25 17:21 UTC, m-strzelczyk commented on .github/CODEOWNERS
> +/functions/**/*                        @GoogleCloudPlatform/torus-dpe @GoogleCloudPlatform/python-samples-reviewers @GoogleCloudPlatform/functions-framework-google
Please put the functions team as the first on the list. It's used to assign issues and PRs for review, going from left to right. The smallest group should always be on the left :)

2023-03-31 03:09 UTC, dandhlee reviewed
LGTM - if your team is the first team who should be taking a look at the code then could you also add your team to [`blunderbuss.yml`](https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml)? If not, then fine to just update CODEOWNERS.

2023-04-04 12:52 UTC, m-strzelczyk approved these changes

2023-04-04 12:53 UTC, m-strzelczyk commented
@kenneth-rosario can you reply to Dan's comment?

2023-04-04 17:21 UTC, kenneth-rosario commented
@dandhlee My team will be mostly responsible for keeping the samples up to date.

2023-04-09 14:01 UTC, kweinmeister approved these changes

2023-04-09 14:07 UTC, kweinmeister requested changes
CODEOWNERS looks good, Kenneth!

Re: `blunderbuss.yml`, one more change which will make this seamless is to update the bug auto-assign rules here: https://github.com/GoogleCloudPlatform/python-docs-samples/blob/main/.github/blunderbuss.yml#L23

Basically, you could just pull out `functions` and assign it by default to the Functions GH team you specified here.  We'll be here for additional support, this just ensures the first round of reviews is handled by the self-service team. Thanks!

2023-04-11 23:18 UTC, nicain approved these changes

2023-04-12 20:27 UTC, kweinmeister approved these changes

2023-04-12 20:28 UTC, merged