chore(cloudsql): update samples to gen2 Cloud Functions
GoogleCloudPlatform/python-docs-samples pull request #9854
Opened 2023-05-01 17:25 UTC by jackwotherspoon

Updating Cloud SQL samples to use gen2 Cloud Functions over gen1

2023-05-02 15:45 UTC, enocom requested changes

2023-05-02 15:45 UTC, enocom commented on cloud-sql/postgres/sqlalchemy/README.md
> +Python package, [cloud-sql-python-connector package](https://pypi.org/project/cloud-sql-python-connector/).
Nit: End with a period. And then, "See cloud-sql-python-connector package."

2023-05-02 15:45 UTC, enocom commented on cloud-sql/postgres/sqlalchemy/README.md
> +gcloud sql instances describe <INSTANCE_NAME>
```
gcloud sql instances describe <INSTANCE_NAME> --format='value(connectionName)'
```

is better

2023-05-02 15:45 UTC, enocom commented on cloud-sql/postgres/sqlalchemy/README.md
> +./cloudsql-proxy <PROJECT_ID>:<INSTANCE_REGION>:<INSTANCE_NAME> &
cloud-sql-proxy

2023-05-02 15:45 UTC, enocom commented on cloud-sql/postgres/sqlalchemy/README.md
> +./cloud-sql-proxy --unix-socket=./cloudsql <PROJECT_ID>:<INSTANCE_REGION>:<INSTANCE_NAME> &
--unix-socket /cloudsql

2023-05-02 18:59 UTC, enocom approved these changes

2023-05-03 17:24 UTC, engelke approved these changes

2023-05-03 17:24 UTC, merged